#!/usr/bin/env bash

# Summarize git changes with Fabric
# Usage: aigd [file]

set -e

file=$1

FABRIC_BIN="$HOME/.local/bin/fabric"

if [[ ! -x "$FABRIC_BIN" ]]; then
  echo "Error: fabric hasn't been properly installed"
  exit 1
fi

# Read `git diff` output
if [[ -n "$file" ]]; then
	diff_output=$(git diff "$file")
else
	diff_output=$(git diff) # Reads `git diff` for entire repo
fi

# Exit if there are no changes
if [[ -z "$diff_output" ]]; then
	echo "🌱 No changes to summarise..."
	exit 0
fi

echo "$diff_output" | fabric -p summarize_git_diff

